/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_client_free: (a: number, b: number) => void;
export const client_cars: (a: number, b: number) => [number, number];
export const client_closed: (a: number, b: number, c: number) => void;
export const client_join: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const client_leave: (a: number) => void;
export const client_neutral: (a: number) => void;
export const client_new: () => number;
export const client_on_datagram: (a: number, b: number, c: number, d: number) => void;
export const client_on_stream: (a: number, b: number, c: number, d: number) => [number, number];
export const client_ready: (a: number) => void;
export const client_set_keys: (a: number, b: number, c: number, d: number, e: number) => void;
export const client_take_datagram: (a: number) => [number, number];
export const client_take_stream: (a: number) => [number, number];
export const client_update: (a: number, b: number) => void;
export const client_view: (a: number, b: number) => any;
export const course_geometry: () => any;
export const fixed_dt_seconds: () => number;
export const physics_version: () => number;
export const protocol_version: () => number;
export const reference_join_frame: () => [number, number];
export const reference_state: () => [number, number];
export const tick_hz: () => number;
export const validate: (a: number, b: number, c: number, d: number) => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
